# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/trusty64"

  # Define HostName
  config.vm.define "StormInSide"
  config.vm.hostname = "StormInSide"

  config.vm.network "private_network", ip: "192.168.33.10"



  config.vm.synced_folder ".", "/vagrant_data"


  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = 4
  end


  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
  SHELL
end
